// Unit tests for the X-Plane navdata parsers. Uses an in-memory Drift
// database and synthetic .dat files with lines copied verbatim from a real
// X-Plane 12 / Navigraph installation.

import 'dart:io';

import 'package:drift/native.dart';
import 'package:flight_studio/core/parsing/apt_dat_parser.dart';
import 'package:flight_studio/core/parsing/earth_nav_parser.dart';
import 'package:flight_studio/data/db/database.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  late NavdataDatabase db;
  late Directory tmp;

  setUp(() {
    db = NavdataDatabase(NativeDatabase.memory());
    tmp = Directory.systemTemp.createTempSync('navdata_test');
  });

  tearDown(() async {
    await db.close();
    tmp.deleteSync(recursive: true);
  });

  File writeDat(String name, List<String> lines) {
    final f = File('${tmp.path}/$name');
    f.writeAsStringSync(lines.join('\n'));
    return f;
  }

  test('importEarthNav classifies all navaid types per LNM taxonomy', () async {
    final file = writeDat('earth_nav.dat', [
      'I',
      '1200 Version - data cycle 2607, build 20260701, metadata NavXP1200.',
      // NDB (type 2).
      ' 2  13.845277778   20.845555556        0      350    50      0.000   AB ENRT FT ABECHE NDB',
      // VOR/DME (type 3, name suffix).
      ' 3   9.037805556    7.285111111     1191    11630   130     -0.000  ABC ENRT DN ABUJA VOR/DME',
      // Pure VOR (type 3).
      ' 3  13.846633333   20.863050000        0    11450   130      2.000   AE ENRT FT ABECHE VOR',
      // TACAN (type 3).
      ' 3  11.549222222   43.154861111       40    11460   130      2.000  ABI ENRT HD DJIBOUTI TACAN',
      // VORTAC (type 3) — must NOT be classified as plain TACAN.
      ' 3  47.439300000 -122.308100000      404    11600   145     18.000  SEA ENRT K1 SEATTLE VORTAC',
      // Paired DME (type 12) — must be SKIPPED (duplicate of type 3).
      '12   9.037805556    7.285111111     1191    11630   130      0.000  ABC ENRT DN ABUJA VOR/DME DME',
      // ILS localizer (type 4).
      ' 4  36.710077778    5.053713889       57    11050    18  94221.749   BJ DAAE DA 26 ILS-cat-I',
      // Standalone LOC (type 5).
      ' 5  36.177691667    5.312066667        0    11090    18  96026.861   ST DAAS DA 27 LOC',
      // Glideslope (type 6).
      ' 6  36.712411111    5.079791667       57    11050    18 300261.749   BJ DAAE DA 26 GS',
      // Outer marker (type 7).
      ' 7 -17.994425000   31.027405556        0        0     0     44.814  IHA FVRG FV 05 OM',
      // Middle marker (type 8).
      ' 8 -26.542777778   31.286666667        0        0     0     53.305  IMS FDMS FD 07 MM',
      // Inner marker (type 9).
      ' 9  64.802127778 -147.886813889      430        0     0     38.049 ICNA PAFA PA 02L IM',
      // Standalone DME (type 13).
      '13  28.601750000  -17.756750000      197    11240   130      0.000   BV ENRT GC LA PALMA DME',
      // SBAS final approach point (type 14) — must be SKIPPED.
      '14  28.635934028  -17.755792917      104    47264   0.0    359.019 R36-Z GCLA GC 36 LPV',
      // GLS/GBAS ground station (type 15).
      '15  40.146083333   44.377138889     2921    20731    80 300089.653 G08A UDYZ UD 08 GLS',
      // SBAS threshold (type 16) — must be SKIPPED.
      '16  28.617376389  -17.755430694      104    47264  49.2 300359.019 R36-Z GCLA GC 36 E36A',
      '99',
    ]);

    final count = await importEarthNav(file, db);
    // 1 NDB + 4 VOR family + ILS + LOC + GS + OM + MM + IM + DME + GLS = 13.
    // Skipped: paired DME (12), SBAS points (14, 16).
    expect(count, 13);

    final rows = await db.select(db.navaids).get();
    final byType = <String, int>{};
    for (final r in rows) {
      byType[r.type] = (byType[r.type] ?? 0) + 1;
    }
    expect(byType['NDB'], 1);
    expect(byType['VOR'], 1, reason: 'Pure VOR from name suffix');
    expect(byType['VOR/DME'], 1);
    expect(byType['TACAN'], 1);
    expect(byType['VORTAC'], 1, reason: 'VORTAC must not collapse into TACAN');
    expect(byType['DME'], 1, reason: 'Standalone DME only (paired skipped)');
    expect(byType['ILS'], 1);
    expect(byType['LOC'], 1);
    expect(byType['GS'], 1);
    expect(byType['OM'], 1);
    expect(byType['MM'], 1);
    expect(byType['IM'], 1);
    expect(byType['GLS'], 1);

    final vor = rows.firstWhere((r) => r.type == 'VOR/DME');
    expect(vor.name, 'ABUJA VOR/DME', reason: 'Name starts at parts[10]');
  });

  test('importAptDat parses airports with runway-derived positions', () async {
    final file = writeDat('apt.dat', [
      'A',
      '1200 Generated by WorldEditor',
      // Land airport with one runway (KSEA-like, ~11,900 ft 16L/34R).
      '1   433 1 0 KSEA Seattle-Tacoma Intl',
      '100 45.72 1 0 0.25 0 0 0 16L 47.4556 -122.3078 0 0 1 0 0 0 34R 47.4216 -122.3082 0 0 1 0 0 0',
      '99',
      // Heliport with helipad position (no runways). Header row code = 17.
      '17   10 0 0 XXHeli Test Heliport',
      '102 51.5 -0.1 2 20 0 0 0 0 H',
      '99',
      // Airport with no runway and no helipad — must be skipped.
      '1   100 0 0 NOWAY Positionless',
      '99',
      // Trailing airport without closing 99 — still flushed at EOF.
      '1   50 0 0 EOFAP End Of File',
      '100 30 1 0 0 0 0 0 09 12.0 20.0 0 0 1 0 0 0 27 -12.0 -20.0 0 0 1 0 0 0',
    ]);

    final count = await importAptDat(file, db);
    expect(count, 3, reason: 'KSEA + heliport + EOF airport; NOWAY skipped');

    final airports = await db.select(db.airports).get();
    final ksea = airports.firstWhere((a) => a.icao == 'KSEA');
    expect(ksea.name, 'Seattle-Tacoma Intl');
    expect(ksea.type, 'airport');
    // KSEA position = runway midpoint ≈ (47.4386, -122.3080).
    expect(ksea.latitude, closeTo(47.4386, 0.001));
    expect(ksea.longitude, closeTo(-122.3080, 0.001));

    final heli = airports.firstWhere((a) => a.icao == 'XXHeli');
    expect(heli.type, 'heliport');
    expect(heli.latitude, closeTo(51.5, 0.001));

    // Runways stored with computed heading/length.
    final runways = await db.select(db.runways).get();
    expect(runways, hasLength(2)); // KSEA 16L + EOFAP 09.
    final kseaRw = runways.firstWhere((r) => r.airportIcao == 'KSEA');
    expect(kseaRw.ident, '16L');
    expect(kseaRw.surface, 'asphalt');
    // ~11,900 ft runway.
    expect(kseaRw.lengthFt, greaterThan(10000));
    expect(kseaRw.lengthFt, lessThan(13000));
  });

  test('importEarthAwy parses airway segments', () async {
    final file = writeDat('earth_awy.dat', [
      'I',
      '1100 Version - data cycle 2607, build 20260701, metadata AwyXP1100.',
      '07EBA DT 11 GILEX DT 11 N 1  95 245 G869',
      '5950N BG 11 IDROT BG 11 N 1  28 195 Y689',
      '99',
    ]);

    final count = await importEarthAwy(file, db);
    expect(count, 2);

    final rows = await db.select(db.airways).get();
    final seg = rows.firstWhere((r) => r.name == 'G869');
    expect(seg.startIdent, '07EBA');
    expect(seg.endIdent, 'GILEX');
    expect(seg.direction, 'N');
    expect(seg.baseFlightLevel, 95);
    expect(seg.topFlightLevel, 245);
  });

  test('parsers report progress and tolerate empty files', () async {
    final empty = writeDat('earth_nav.dat', ['I', '99']);
    final progressLines = <String>[];
    final count = await importEarthNav(
      empty,
      db,
      onProgress: (_, _, msg) {
        progressLines.add(msg);
      },
    );
    expect(count, 0);
    expect(progressLines, isNotEmpty);
  });
}
